"""Add width_mm and width_effective_mm to PartnerPriceItem

Revision ID: 052736c042b1
Revises: be0369704578
Create Date: 2026-09-11 07:21:37.000956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052736c042b1'
down_revision: Union[str, None] = 'be0369704578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_price_items', sa.Column('width_mm', sa.Numeric(precision=7, scale=2), nullable=True))
    op.add_column('partner_price_items', sa.Column('width_effective_mm', sa.Numeric(precision=7, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('partner_price_items', 'width_effective_mm')
    op.drop_column('partner_price_items', 'width_mm')
    # ### end Alembic commands ###
