"""Add delivery_note_filename to Document and sharepoint_subfolder_realizace_id to Deal

Revision ID: 0963e3210a1e
Revises: f24a5aafa811
Create Date: 2026-09-03 10:38:20.211140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0963e3210a1e'
down_revision: Union[str, None] = 'f24a5aafa811'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
