"""Add reminder_sent_at to Document

Revision ID: 294052b49710
Revises: 624c1a041cc0
Create Date: 2026-08-18 10:43:57.621446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294052b49710'
down_revision: Union[str, None] = '624c1a041cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'reminder_sent_at')
    # ### end Alembic commands ###
