"""Add avatar_filename to User

Revision ID: 2bdf055a8d80
Revises: 5ff6512ac0d9
Create Date: 2026-09-05 04:27:11.412301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bdf055a8d80'
down_revision: Union[str, None] = '5ff6512ac0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_filename')
    # ### end Alembic commands ###
