"""Add synced_to_sharepoint_at to DealAttachment

Revision ID: 49f61b175378
Revises: 5384ff67a59b
Create Date: 2026-09-22 04:59:55.119366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f61b175378'
down_revision: Union[str, None] = '5384ff67a59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal_attachments', sa.Column('synced_to_sharepoint_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal_attachments', 'synced_to_sharepoint_at')
    # ### end Alembic commands ###
