"""Add wood_species_id to CalculationItem

Revision ID: 5384ff67a59b
Revises: f6a7b8c9d0e1
Create Date: 2026-09-21 12:16:16.997376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5384ff67a59b'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculation_items', sa.Column('wood_species_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'calculation_items', 'wood_species', ['wood_species_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'calculation_items', type_='foreignkey')
    op.drop_column('calculation_items', 'wood_species_id')
    # ### end Alembic commands ###
