"""Add delivery note fields actual

Revision ID: 5ff6512ac0d9
Revises: 0963e3210a1e
Create Date: 2026-09-03 10:45:25.803004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ff6512ac0d9'
down_revision: Union[str, None] = '0963e3210a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('sharepoint_subfolder_realizace_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('delivery_note_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'delivery_note_filename')
    op.drop_column('deals', 'sharepoint_subfolder_realizace_id')
    # ### end Alembic commands ###
