"""Add delivery_terms and payment_terms to Calculation

Revision ID: 60deb6967835
Revises: 7641b9024a19
Create Date: 2026-08-21 07:15:51.659832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60deb6967835'
down_revision: Union[str, None] = '7641b9024a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculations', sa.Column('delivery_terms', sa.String(length=255), nullable=True))
    op.add_column('calculations', sa.Column('payment_terms', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calculations', 'payment_terms')
    op.drop_column('calculations', 'delivery_terms')
    # ### end Alembic commands ###
