"""Add valid_until to Calculation

Revision ID: 619b4d606f9c
Revises: 294052b49710
Create Date: 2026-08-20 07:57:11.558255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '619b4d606f9c'
down_revision: Union[str, None] = '294052b49710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculations', sa.Column('valid_until', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calculations', 'valid_until')
    # ### end Alembic commands ###
