"""No schema changes - calculation/document endpoints

Revision ID: 624c1a041cc0
Revises: 0a9a09cef7b0
Create Date: 2026-08-18 08:59:13.263089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624c1a041cc0'
down_revision: Union[str, None] = '0a9a09cef7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
