"""Add iDoklad fields to Company and Document

Revision ID: 66c96cdda232
Revises: 55fd019d3f55
Create Date: 2026-08-28 11:40:52.071478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66c96cdda232'
down_revision: Union[str, None] = '55fd019d3f55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('idoklad_contact_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('idoklad_invoice_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('idoklad_invoice_number', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('idoklad_pdf_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'idoklad_pdf_url')
    op.drop_column('documents', 'idoklad_invoice_number')
    op.drop_column('documents', 'idoklad_invoice_id')
    op.drop_column('companies', 'idoklad_contact_id')
    # ### end Alembic commands ###
