"""Add WoodSpecies and PricingParameter tables

Revision ID: 7641b9024a19
Revises: b60fe8f3adfb
Create Date: 2026-08-20 13:39:50.249299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7641b9024a19'
down_revision: Union[str, None] = 'b60fe8f3adfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_parameters',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('wood_species',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('width_effective_mm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('length_mm', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('thickness_mm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('purchase_price_per_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wood_species')
    op.drop_table('pricing_parameters')
    # ### end Alembic commands ###
