"""Add sharepoint_folder_year and sharepoint_folder_number to Deal

Revision ID: 77261893949e
Revises: 1c77ab4e804e
Create Date: 2026-09-01 06:21:28.246259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77261893949e'
down_revision: Union[str, None] = '1c77ab4e804e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
