"""Add owner_user_id to Deal

Revision ID: 797c7e210c4d
Revises: bce91391b484
Create Date: 2026-08-25 05:48:17.166572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797c7e210c4d'
down_revision: Union[str, None] = 'bce91391b484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('owner_user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'deals', 'users', ['owner_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'owner_user_id')
    # ### end Alembic commands ###
