"""Add is_task and due_date to DealNote

Revision ID: a1b2c3d4e5f6
Revises: 052736c042b1
Create Date: 2026-09-12 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '052736c042b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal_notes', sa.Column('is_task', sa.Boolean(), nullable=True))
    op.add_column('deal_notes', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deal_notes', 'due_date')
    op.drop_column('deal_notes', 'is_task')
    # ### end Alembic commands ###
