"""Add CalculationItem and discount fields

Revision ID: b60fe8f3adfb
Revises: 619b4d606f9c
Create Date: 2026-08-20 09:16:04.361645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b60fe8f3adfb'
down_revision: Union[str, None] = '619b4d606f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calculation_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('MATERIAL', 'PRACE', 'DOPRAVA', 'OSTATNI', name='itemcategory'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('calculations', sa.Column('discount_material_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    op.add_column('calculations', sa.Column('discount_installation_percent', sa.Numeric(precision=5, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calculations', 'discount_installation_percent')
    op.drop_column('calculations', 'discount_material_percent')
    op.drop_table('calculation_items')
    # ### end Alembic commands ###
