"""Add invoice_pdf_filename and invoice_sent_at to Document

Revision ID: b7474b2432ca
Revises: 66c96cdda232
Create Date: 2026-08-29 04:40:47.884934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7474b2432ca'
down_revision: Union[str, None] = '66c96cdda232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('invoice_pdf_filename', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('invoice_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'invoice_sent_at')
    op.drop_column('documents', 'invoice_pdf_filename')
    # ### end Alembic commands ###
