"""Add partner_price_items table

Revision ID: be0369704578
Revises: d84ba2047495
Create Date: 2026-09-11 06:55:18.094838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0369704578'
down_revision: Union[str, None] = 'd84ba2047495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_price_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('wood_type', sa.String(length=100), nullable=True),
    sa.Column('dimensions', sa.String(length=50), nullable=True),
    sa.Column('profile', sa.String(length=100), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('surface', sa.String(length=255), nullable=True),
    sa.Column('service_price_per_m2', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partner_price_items')
    # ### end Alembic commands ###
