"""Add Calculation, Document, DocumentView, EmailTemplate

Revision ID: d5187fe76fa6
Revises: a595618f6324
Create Date: 2026-08-18 06:36:26.143677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5187fe76fa6'
down_revision: Union[str, None] = 'a595618f6324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('product_line', sa.String(length=50), nullable=True),
    sa.Column('wood_species', sa.String(length=255), nullable=True),
    sa.Column('area_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('price_without_vat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_with_vat', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_price_per_m2', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('margin_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('raw_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deal_id', sa.UUID(), nullable=False),
    sa.Column('calculation_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('NABIDKA', 'OBJEDNAVKA', 'ZALOHOVA_FAKTURA', 'DODACI_LIST', 'FINALNI_FAKTURA', name='documenttype'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=64), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calculation_id'], ['calculations.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_table('document_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_views')
    op.drop_table('documents')
    op.drop_table('calculations')
    op.drop_table('email_templates')
    # ### end Alembic commands ###
