"""Add is_partner to Company and PartnerPriceItem table

Revision ID: d84ba2047495
Revises: ea159dc6af34
Create Date: 2026-09-11 06:47:02.509008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84ba2047495'
down_revision: Union[str, None] = 'ea159dc6af34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('is_partner', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'is_partner')
    # ### end Alembic commands ###
