"""Add confirmation evidence fields (IP, VOP snapshot, smlouvy subfolder)

Revision ID: dded0202412e
Revises: ee174b3b3a39
Create Date: 2026-09-24 13:15:29.055526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dded0202412e'
down_revision: Union[str, None] = 'ee174b3b3a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('sharepoint_subfolder_smlouvy_id', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('confirmation_ip_address', sa.String(length=45), nullable=True))
    op.add_column('documents', sa.Column('vop_snapshot_filename', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('vop_snapshot_sha256', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'vop_snapshot_sha256')
    op.drop_column('documents', 'vop_snapshot_filename')
    op.drop_column('documents', 'confirmation_ip_address')
    op.drop_column('deals', 'sharepoint_subfolder_smlouvy_id')
    # ### end Alembic commands ###
