"""Add SharePoint fields to Deal, FolderSequence table

Revision ID: e2fc4e6ac455
Revises: b7474b2432ca
Create Date: 2026-08-29 09:00:58.706318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2fc4e6ac455'
down_revision: Union[str, None] = 'b7474b2432ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_sequences',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.add_column('deals', sa.Column('sharepoint_folder_url', sa.String(length=500), nullable=True))
    op.add_column('deals', sa.Column('sharepoint_folder_id', sa.String(length=255), nullable=True))
    op.add_column('deals', sa.Column('sharepoint_drive_id', sa.String(length=255), nullable=True))
    op.add_column('deals', sa.Column('sharepoint_subfolder_nabidka_id', sa.String(length=255), nullable=True))
    op.add_column('deals', sa.Column('sharepoint_subfolder_fakturace_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'sharepoint_subfolder_fakturace_id')
    op.drop_column('deals', 'sharepoint_subfolder_nabidka_id')
    op.drop_column('deals', 'sharepoint_drive_id')
    op.drop_column('deals', 'sharepoint_folder_id')
    op.drop_column('deals', 'sharepoint_folder_url')
    op.drop_table('folder_sequences')
    # ### end Alembic commands ###
