"""Add next_contact_date and next_contact_notified_at to Deal

Revision ID: ea159dc6af34
Revises: f6cfa3f1de53
Create Date: 2026-09-10 08:00:05.583019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea159dc6af34'
down_revision: Union[str, None] = 'f6cfa3f1de53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('next_contact_date', sa.Date(), nullable=True))
    op.add_column('deals', sa.Column('next_contact_notified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'next_contact_notified_at')
    op.drop_column('deals', 'next_contact_date')
    # ### end Alembic commands ###
