"""Add confirmation evidence fields (IP, VOP snapshot, smlouvy subfolder)

Revision ID: ee174b3b3a39
Revises: 49f61b175378
Create Date: 2026-09-24 13:12:57.267501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee174b3b3a39'
down_revision: Union[str, None] = '49f61b175378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
