"""Add sharepoint_folder_year and sharepoint_folder_number to Deal (actual)

Revision ID: f24a5aafa811
Revises: 77261893949e
Create Date: 2026-09-01 06:26:34.500977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24a5aafa811'
down_revision: Union[str, None] = '77261893949e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('sharepoint_folder_year', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('sharepoint_folder_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'sharepoint_folder_number')
    op.drop_column('deals', 'sharepoint_folder_year')
    # ### end Alembic commands ###
