"""Add density_kg_per_m3 to WoodSpecies

Revision ID: f6cfa3f1de53
Revises: d2a539682be7
Create Date: 2026-09-07 09:05:25.463917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6cfa3f1de53'
down_revision: Union[str, None] = 'd2a539682be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wood_species', sa.Column('density_kg_per_m3', sa.Numeric(precision=7, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wood_species', 'density_kg_per_m3')
    # ### end Alembic commands ###
