"""Add confirmed_at and confirmed_by_name to Document

Revision ID: f86cd4b5ebb1
Revises: 60deb6967835
Create Date: 2026-08-24 10:41:05.758264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86cd4b5ebb1'
down_revision: Union[str, None] = '60deb6967835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('documents', sa.Column('confirmed_by_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'confirmed_by_name')
    op.drop_column('documents', 'confirmed_at')
    # ### end Alembic commands ###
